lightpanda-io/browser

- src/apiweb.zig
- src/browser/browser.zig
- src/dom/comment.zig
- src/dom/document.zig
- src/dom/document_fragment.zig
- src/dom/implementation.zig
- src/dom/node.zig
- src/dom/text.zig
- src/main.zig
- src/main_get.zig
- src/main_shell.zig
- src/main_wpt.zig
- src/netsurf.zig
- src/run_tests.zig
- src/test_runner.zig
- src/user_context.zig
- src/wpt/run.zig
- src/xhr/xhr.zig
fix #102
depends on https://github.com/lightpanda-io/libdom/pull/14
depends on https://github.com/lightpanda-io/jsruntime-lib/pull/220
> Add user context

- src/netsurf.zig
> event: log listeners errors and continue execution

- src/browser/browser.zig
- src/main_get.zig
depends on https://github.com/lightpanda-io/jsruntime-lib/pull/226
> browser: extract loop wait

- .github/workflows/wpt.yml
- .github/workflows/zig-test.yml
It seems docker blocks io_uring by default using seccomp.
see tigerbeetle/tigerbeetle#1995 and moby/moby#46762
relates with https://github.com/lightpanda-io/zig-js-runtime/issues/232
> ci: add --security-opt seccomp=unconfined docker option

- src/dom/event_target.zig
- src/events/event.zig
- src/netsurf/netsurf.zig
- src/xhr/event_target.zig
It simplifies the EventHandlerFunc creation and allows to insert user's data.
> events: create an EventHandlerData struct

- src/dom/dom.zig
- src/dom/element.zig
- src/dom/mutation_observer.zig
- src/netsurf/netsurf.zig
- src/run_tests.zig
> dom: implement MutationObserver

- src/browser/browser.zig
http client depends on io loop and must be deinit before.
fix #261
> browser: fix invalid deinit order

- .github/workflows/build.yml
The `-Dcpu` option force compiling using less CPU's capabilities. This will improve the binary compatibility with older CPUs.
Relates with #264
> ci: target cpu x86_64 to improve CPU compat

- src/cdp/cdp.zig
- src/cdp/page.zig
- src/cdp/target.zig
- src/msg.zig
- src/server.zig
This PR ensure that all read and write I/O are done asynchronously:
- on the `readCbk` the next read is sent to the kernel _before_ doing the actual command work (so both are concurrent)
- on the write part the `sendSync` command was removed in favor of the `sendAsync`
> Cdp full async

- src/server.zig
Needs https://github.com/lightpanda-io/tigerbeetle-io/pull/11
> Fix cdp full async

- Dockerfile
remove following the warning
```
1 warning found (use docker --debug to expand):
- WorkdirRelativePath: Relative workdir "browser" can have unexpected results if the base image changes (line 48)
```
> docker: use absolute path with WORKDIR

- src/cdp/target.zig
https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget
> cdp: browserContextId is optional in Target.createTarget

- .github/workflows/build.yml
- .github/workflows/wpt.yml
- .github/workflows/zig-test.yml
The repos are public now, we don't need the token anymore to fetch.
> ci: remove useless token

- Makefile
This PR fixes the download URL for zig in the Makefile's download-zig rule.
> fix Makefile download-zig: url changed

- src/main.zig
use `--verbose` to enable debug output.
In debug mode, verbose is forced to `true`.
> add --verbose option

- src/cdp/cdp.zig
- src/cdp/msg.zig
- src/cdp/target.zig
> cdp: add TargetCreated event on createTarget message

- .github/actions/install/action.yml
- src/browser/browser.zig
- src/html/history.zig
relates with #342 
depends on https://github.com/lightpanda-io/zig-js-runtime/pull/262
> browser: support for modules

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/page.zig
- src/cdp/runtime.zig
- src/cdp/target.zig
- src/main.zig
- src/server.zig
Effort to accept the command `cdpcli -verbose -cdp ws://127.0.0.1:9222/devtools/browser/main -runs=1 eval`.
> cdp: cdpcli compatibility

- src/browser/browser.zig
- src/html/document.zig
- src/html/html.zig
- src/html/location.zig
- src/html/window.zig
- src/main_shell.zig
- src/netsurf/netsurf.zig
- src/run_tests.zig
- src/wpt/run.zig
depends on https://github.com/lightpanda-io/libdom/pull/21
> dom: first draft for location

- .gitmodules
Allows easily building the project, following the steps in readme, without a github account or having some special git configuration.
If this change is acceptable, I can submit a similar PR for https://github.com/lightpanda-io/zig-js-runtime/blob/main/.gitmodules
> Use https:// instead of git@ for submodules

- src/apiweb.zig
- src/browser/dump.zig
- src/dom/element.zig
- src/run_tests.zig
- src/xmlserializer/xmlserializer.zig
> implement XMLSerializer

- src/apiweb.zig
- src/browser/dump.zig
- src/dom/character_data.zig
- src/dom/dom.zig
- src/dom/mutation_observer.zig
- src/dom/node.zig
- src/dom/nodelist.zig
- src/dom/text.zig
- src/events/event.zig
- src/generate.zig
- src/html/elements.zig
- src/html/html.zig
- src/iterator/iterator.zig
- src/run_tests.zig
- src/storage/storage.zig
- src/url/url.zig
- src/xhr/xhr.zig
- src/xmlserializer/xmlserializer.zig
Leverage comptime fields to give generated Tuple a default value, allowing TupleT and Tuple to be merged.
Only call generate.Tuple on the final output. This eliminates redundant deduplication, and results in a simpler API (nested types just need to expose a natural Zig tuple).
generate.Union leverages the new Tuple and removes unused features.
> Tweak generate.Tuple and generate.Union

- src/browser/mime.zig
- src/str/parser.zig
- src/url/query.zig
1- Remove `parser.trim`, it was only being used in 1 place. All other places
are using `std.mem.trim(u8, X, &std.ascii.whitespace)`, so i updated MIME to
use this as well
2- Use slightly more meaningful field name, i => pos, s = data
3- Leverage std.mem.indexOfScalarPos which can be more efficient for longer
inputs (since it leverages SIMD)
> Minor Reader tweaks

- src/browser/browser.zig
- src/browser/mime.zig
- src/str/parser.zig
- src/xhr/xhr.zig
Common cases, text/html, text/xml and text/plain parse about 2x faster. Other cases are about 30% faster.
Support quoted attributes, i.e. charset="utf-8" & valid escape sequences. This potentially requires allocation, thus Mime.parse now takes an allocator.
Stricter validation around type/subtype based on RFC.
More tests.
Replace Mime.eql with isHTML(). Equality is complicated and was previously incorrect (it was case sensitive, it should not be). Since we currently only use isHTML-like behavior, built a (faster) method specifically for that.
> Improve performance & compliance of MIME parsing

- src/str/parser.zig
- src/url/query.zig
(I accidentally deleted my branch on github, and it closed the original PR (https://github.com/lightpanda-io/browser/pull/410))
1 - Use getOrPut to avoid making 2 map lookups where possible.
2 - Use an arena allocator for Values, which makes memory management simpler.
3 - Because of #2, we no longer need to allocate key or values which don't need
to be unescaped. The downside is that the input string has to outlive the
query.Values (but I think this is currently always the case)
4 - Optimize unescape logic & allocations
5 - Improve test coverage
> Improve memory and performance of url.Query

- src/browser/browser.zig
- src/main_tests.zig
- src/server.zig
- src/unit_tests.zig
https://github.com/lightpanda-io/browser/issues/425
Add a few integration tests for the TCP server which are fast enough to be run as part of the unit tests (one of the new tests covers the above issue).
> Fix server hang on client disconnect

- src/main.zig
I'm not sure if the `page_allocator` was chosen for a specific reason, but I've always heard that the GPA should be used in debug/test, and the c_allocator in release.
> In release mode, switch from page_allocator to c_allocator

- src/server.zig
Results in undefined behavior when a client disconnects and another reconnects while the timeout is being monitored:
Unblocks https://github.com/lightpanda-io/browser/pull/436
> Don't share or reuse timeout_completion

- src/server.zig
For the time being, given that we only allow 1 client at a time, I took a shortcut to implement this. The server has an incrementing "current_client_id" which is part of every completion. On completion callback, we just check if its client_id is still equal to the server's current_client_id.
> Ensure completions are executed on the currently connected client

- src/cdp/browser.zig
- src/cdp/cdp.zig
- src/cdp/testing.zig
- src/server.zig
- src/unit_tests.zig
The change look bigger than it is because the CDP struct was changed into a generic (so that mocks could be injected). This added a level of indentation.
Added a couple tests to get the ball rolling
> Turn CDP into a generic so that mocks can be injected for testing

- src/id.zig
Create UUID v4.
Create prefixed ids. To support more of the CDP protocol, we need to remove the hard-coded IDs (session, browser context, frame, loader, ...) and be able to dynamically create them, i.e. creating a new BrowserContextId when Target.createBrowserContext is called.
```zig
var frame_id = Incremental(u16, "FRM"){};
frame_id.next() == "FRM-1"
frame_id.next() == "FRM-2"
```
Generation is allocation-free (the returned string is only valid until the next call to next()). This is not thread safe, each CDP instance will have its own generator (for each id it needs to generate).
The generated IDs are different than what Chrome uses, i.e. BROWSERSESSIONID597D9875C664CAC0. I looked at various drivers and none have any expectations beyond a string. Shorter IDs will be more efficient. …
> Add an id generator

- src/log.zig
- src/unit_tests.zig
In debug mode, it has a more user-friendly output:
level | the log messge | ms since last message | key=value key=value
In release mode, it logs using logfmt, which is supported by most log ingestion frameworks.
Not being used anywhere right now, keeping this PR small with no impact on existing code.
> Add a structured logger

- .github/workflows/e2e-test.yml
- Dockerfile
- README.md
- src/main.zig
Changes are fairly superfluous. I wanted to remove the error.NoError, but then thought having more explicit command -> options might be good (especially if we add more command and/or options).
I also dupe the string arguments (i.e. `host`). While not duping them is safe on linux/darwin, it isn't clear to me from the documentation that this is guaranteed.
> Add explicit commands to binary

- src/main.zig
Just ran into this testing stuff and trying a `--timeout 300`. Don't see a reason to limit this to 255 seconds.
> allow longer timeouts (u8 -> u16)

- src/browser/browser.zig
- src/cdp/browser.zig
- src/cdp/cdp.zig
- src/cdp/css.zig
- src/cdp/dom.zig
- src/cdp/emulation.zig
- src/cdp/fetch.zig
- src/cdp/inspector.zig
- src/cdp/log.zig
- src/cdp/network.zig
- src/cdp/page.zig
- src/cdp/performance.zig
- src/cdp/runtime.zig
- src/cdp/security.zig
- src/cdp/target.zig
- src/cdp/testing.zig
- src/id.zig
Replace #451 
The TL;DR is that this commit enforces the use of correct IDs, introduces a BrowserContext, and adds some CDP tests.
These are the ids we need to be aware of when talking about CDP:
- id
- browserContextId
- targetId
- sessionId
- loaderId
- frameId
The `id` is the only one that _should_ originate from the driver. It's attached to most messages and it's how we maintain a request -> response flow: when the server responds to a specific message, it echo's back the id from the requested message. (As opposed to out-of-band events sent from the server which won't have an `id`). When I say "id" from this point forward, I mean every id except for this req->res id.
Every other id is created by the browser.
Prior to this commit, we didn't really check incoming ids from the driver. If …
> Make CDP server more authoritative with respect to IDs

- .github/workflows/e2e-test.yml
- src/browser/browser.zig
Relates with https://github.com/lightpanda-io/zig-js-runtime/pull/281
> Reset loop event after page stop.

- src/cdp/cdp.zig
- src/cdp/page.zig
- src/cdp/runtime.zig
- src/cdp/target.zig
- src/cdp/testing.zig
I don't know if FrameId is related to an <iframe>, and whether each Page has 1 implicit "frame". But, playwright seems to treat frameId and targetId as interchangeable, and chrome seems to agree (at leas to some degree); chrome will return a targetId and reuse that value for the frameId.
So the simplest solution is just to remove our concept of a frameId and use targetId exclusively. This doesn't seem to cause any issues with puppeteer.
> Remove CDP FrameId

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/target.zig
- src/cdp/testing.zig
- src/html/window.zig
- src/main.zig
The two bigger changes here are:
1- The http_client has been moved from the Session to the Browser, allowing
its connection pool to be re-used across multiple sessions
2- The browser now has a page_arena which is used for all page-level allocation
and which can be re-used between pages (currently retains 1MB of memory).
Previously, pages uses an arena that was tied to the lifetime of the page,
thus it could not be re-used.
Using the Bench allocator for zig-js-runtime, allocated bytes went from 1347037879 to 834932438 (in a RUNS=1000 of puppeteer demo).
Various other changes to try to simplify the API and remove the possibility of invalid states. For example, session.newPage() now includes the logic for page.start() so that there should now never be a page that wasn't started.
> Optimize memory usage

- src/browser/browser.zig
> browser: fix module URL resolution

- .github/workflows/e2e-test.yml
- .gitignore
- README.md
- src/app.zig
- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/testing.zig
- src/id.zig
- src/main.zig
- src/server.zig
- src/telemetry/lightpanda.zig
- src/telemetry/telemetry.zig
- src/unit_tests.zig
Sends basic usage telemetry. Final URL will need to be changed (probably).
Added Telemetry section to readme (please review). And I the Privacy Policy (linked from the readme)  might need updating to reflect this collection?
Currently, most things need an `Allocator` and `Loop` to run. Now we also need a `Telemetry`, and it isn't hard to imagine a not-so-distant future where various parts also need access to a `Config`. Rather than adding more and more parameters, I've introduced an `App` which is meant to group global data into a single variable, so that future additions are less likely to require touching so much code. Besides this change, the Telemetry code is relatively standalone.
> Add Usage Telemetry

- src/cdp/cdp.zig
- src/cdp/target.zig
> cdp: implement target.setAutoAttach and target.detachFromTarget

- .github/actions/install/action.yml
- .github/workflows/build.yml
- Dockerfile
> ci: use ubuntu 22.04 for x86_64 build

- src/app.zig
- src/telemetry/telemetry.zig
https://github.com/lightpanda-io/browser/issues/486
> Use makePath to create any missing intermediate directories for app dir

- src/browser/browser.zig
- src/cdp/runtime.zig
- src/cdp/testing.zig
This PR run v8 micro tasks after we send a script to the inspector and removes the `async=false` cdp hack.
It depends on https://github.com/lightpanda-io/zig-js-runtime/pull/291 which also runs the micro tasks every  millisecond.
> run v8 micro tasks

- src/server.zig
Solves slow startup time with chromedp
> On a non websocket upgrade connection, close the connection

- src/browser/browser.zig
- src/http/client.zig
- src/main_tests.zig
- src/storage/cookie.zig
- src/storage/storage.zig
- src/user_context.zig
- src/wpt/run.zig
- src/xhr/xhr.zig
PR is built on top of https://github.com/lightpanda-io/browser/pull/482. I'd rather merge that first (since it's quite large).
This code is otherwise ready, so I wanted to open the PR in case anyone is eager to review.
> Add Cookie support to browser & xhr requests

- src/browser/browser.zig
```
$ zig build run -- fetch  http://www.urlfilterdb.com/
debug(cli): Fetch mode: url http://www.urlfilterdb.com/, dump false
debug(browser): start js env
debug(browser): setup global env
debug(polyfill): load polyfill-fetch: undefined
debug(browser): inspector context created
debug: Inspector contextCreated called
debug(browser): starting GET http://www.urlfilterdb.com/
info(http_client): redirecting to: GET https://www.urlfilterdb.com/
info(browser): GET https://www.urlfilterdb.com/ 200
debug(browser): header content-type: text/html; charset=utf-8
debug(browser): parse html with charset utf-8
debug(browser): inspector context created
debug: Inspector contextCreated called
debug(browser): wait: OK
```
> browser: update urls after redirection

- src/cdp/Node.zig
- src/cdp/cdp.zig
- src/cdp/domains/dom.zig
- src/cdp/testing.zig
- src/testing.zig
Add child nodes to CDP registry.
Add custom CDP Node writer to deal with different messages requiring a different representation (i.e. differnent child depth) of a node.
> Cdp node children

- src/html/document.zig
Subtype is now supported in zig-v8-fork and zig-js-runtime, adding the declaration to the HTMLDocument which is unblocks the `DOM.getDocument` cdp message.
> add 'node' subtype to htmldocument

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/input.zig
- src/cdp/domains/page.zig
- src/cdp/domains/target.zig
- src/cdp/testing.zig
- src/dom/element.zig
- src/main_tests.zig
- src/netsurf/netsurf.zig
- src/user_context.zig
This isn't complete.
Can't test because scripts run into other blockers before reaching this point (i.e. Dom.resolveNode). I do think it's pretty safe to merge this as-is though.
Looking for feedback on the `FlatRenderer` in `browser.zig` and Page.click handling (netsurf code is a bit tedious to us).
Besides the inability to manually test. I'm also looking for feedback about how to test this. These flows are starting to get more complicated and I'm not sure they're reasonable for unit tests.
> Add a dumb renderer to get coordinates

- src/cdp/domains/dom.zig
- src/cdp/testing.zig
ResolveNode implementation.
This PR is only changing CDP DOM, other changes come from https://github.com/lightpanda-io/browser/pull/502 including current nullptr issue
Depends on:
- https://github.com/lightpanda-io/browser/pull/502
- https://github.com/lightpanda-io/zig-js-runtime/pull/301
> Resolve node

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/input.zig
- src/cdp/testing.zig
- src/html/location.zig
- src/html/window.zig
- src/http/client.zig
- src/main_tests.zig
- src/storage/cookie.zig
- src/telemetry/lightpanda.zig
- src/url.zig
- src/url/url.zig
- src/user_context.zig
- src/wpt/run.zig
- src/xhr/xhr.zig
`Page` currently contains 5 URL-ish related fields:
```zig
rawuri: ?[]const u8 = null,
uri: std.Uri = undefined,
origin: ?[]const u8 = null,
url: ?URL = null,
location: Location = .{},
```
This PR adds a new URL struct which contains both the raw string and the `std.Uri`, and encapsulates some of the `std.Uri` API. It also tries to clean up some of the ownership. For example, `page` no longer has a `location` field. Instead, the window owns the location. Similarly, `page` no longer has a `url` field, the location now owns its url.
I original made http/client.zig and storage/cookie.zig use the new URL struct, but I backed away from that change in this PR. However, I did change those two classes to use  `*const std.Uri` rather than a `std.Uri`, again to try to clean up ownership.
I think …
> Add URL struct

- src/wpt/run.zig
https://github.com/lightpanda-io/zig-js-runtime/commit/40c0c7d4218fd6c79775b3751fe5fc4806ea24e8
Makes it unecessary as wait is now always called on deinit.
> Remove the WPT js_env.wait() on error.

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/page.zig
- src/cdp/testing.zig
- src/main.zig
- src/notification.zig
https://github.com/lightpanda-io/browser/pull/516 needs a way for the page/session to communicate with CDP (i.e. the client). This adds a very simple mechanism for the page/session to callback into CDP. 
The `Page.navigate` CDP message has been changed to use the new notification appraoch. Page.navigate just signals the navigation request, and it's only via notifications from the page/session that page lifecycle events are sent back to the client.
I know this isn't the holistic event system that we want. This isn't something that the HTTP client can use to emit events nor is it something that telemetry can register listeners with. My goal is to get clicks working (from mouse events and javascript), then add some type of integration testing. Most of our recent additions don't have great …
> Communicate page navigation state via notifications

- src/browser/dom/node.zig
- src/testing.zig
- src/wpt/run.zig
Having a js source name is useful to detect where the error comes from.
Using `null` generates messages with `<anonymous>` source name.
eg. `ReferenceError: report is not defined\n    at <anonymous>:1:1`
vs. `ReferenceError: report is not defined\n    at teststatus:1:1`
> test: re-introduce js source name

- README.md
Adding a note to indicate that Lightpanda works on WSL
Alternative text:
> Install & open WSL + Ubuntu:
>   1. `wsl --install`
>   2. -- restart --
>   3. `wsl --install -d Ubuntu`
>   4. `wsl`
> 
>   Inside WSL install the Lightpanda browser:
>   ```console
>   curl -L -o lightpanda https://github.com/lightpanda-io/browser/releases/download/nightly/lightpanda-x86_64-linux && \
>   chmod a+x ./lightpanda
>   ```
>   It is recommended to install clients like Puppeteer on the Windows host.
> WSL support note

- src/http/client.zig
The HTTP response values _are_ mutable, but because we're using std.http.Header the type is a `[]const u8`. This introduce a custom `Header` type where the value is `[]u8`.
The goal is largely to allow more efficient value-comparison, by allowing calling code to lower-case in-place. I specifically have the Mime parser in mind:
https://github.com/lightpanda-io/browser/blob/25dcae76487ab2aaa8ac8b468f465e55007a76ee/src/browser/mime.zig#L134
> Make HTTP Response header values mutable

- src/browser/dom/node.zig
These are used by puppeteer when it's trying to execute code to trigger a click.
> Add Node.$NODE_TYPE class attributes

- src/browser/browser.zig
- src/browser/dom/mutation_observer.zig
- src/browser/events/event.zig
- src/browser/html/elements.zig
- src/browser/netsurf.zig
- src/cdp/domains/page.zig
- src/cdp/testing.zig
- src/events/event.zig
- src/main.zig
- src/notification.zig
- src/url.zig
Add _click handler to HTMLElement
Register zig click listener on document.
Largely waiting on https://github.com/lightpanda-io/browser/pull/501/files to finalize the placeholders.
> Add zig listener support to netsurf event handler

- src/browser/dom/dom.zig
- src/browser/dom/html_collection.zig
- src/browser/dom/mutation_observer.zig
- src/browser/dom/nodelist.zig
- src/browser/dom/token_list.zig
- src/browser/env.zig
- src/browser/iterator/iterator.zig
- src/browser/netsurf.zig
- src/runtime/js.zig
Add value setter, keys(), values(), entries() and forEach().
~Like nodelist, forEach still doesn't support `this` arg (gotta think about how to do this).~
I think these iterable methods are missing in a few places, so I added a generic Entries iterator and a generic Iterable.
jsruntime will now map a Zig tuple to a JS array.
> Add missing TokenList APIs

- src/browser/dom/implementation.zig
- src/runtime/js.zig
- src/runtime/test_primitive_types.zig
Some APIs need a null-terminated string. Currently, they have to ask for a `[]const u8` and then convert it to a `[:0]const u8`. This is 2 allocations: 1 for jsruntime to get the `[]const u8` from v8, and then one to get the [:0]. By supporting `[:0]const u8` directly, this is now a single allocation.
> Support binding JS strings to [:0]const u8

- .github/actions/install/action.yml
- Dockerfile
- build.zig.zon
- src/cdp/domains/dom.zig
- src/cdp/testing.zig
- src/runtime/js.zig
Replaces: https://github.com/lightpanda-io/browser/pull/524
> descibeNode for new js runtime

- src/browser/dom/mutation_observer.zig
- src/runtime/js.zig
Because of callbacks, calls into Zig can be nested. Previously, the call_arena was reset after _every_ call. When calls are nested, this doesn't work - the nested call resets the arena, which the caller might still need. A `call_depth` integer was added to the Executor. Each call starts by incrementing the call_depth and, on deinit, decrements the call_depth. The call_arena is only reset when the call_depth == 0. This could result in lower memory use.
Also promoted the call_arena and scope_arena to the Env. Practically speaking, nothing has changed, since they're still reset under the exact same conditions. However, when an executor ends and a new one is started, it can now reuse the retained_capacity of the previous arenas. This should result in fewer allocations.
> Re-introduce call_arena

- src/browser/browser.zig
- src/browser/mime.zig
- src/browser/xhr/xhr.zig
- src/http/client.zig
- src/testing.zig
Synchronous body reader now exposes a peek() function to get the first few bytes from the response body. This will be no less than 100 bytes (assuming the body is that big), but could be more. Streaming API, via res.next() continues to work as-is even if peek() is called.
Introduce Mime.sniff() that detects a few common types - the ones that we care about right now - from the body content.
The original Mime.parse() has also been optimized to take advantage of the fact that the provided content_type is now mutable (went from `[]const u8` to `[]u8`).
> Try to sniff the mime type based on the body content

- src/browser/dom/character_data.zig
- src/browser/dom/document_fragment.zig
- src/browser/dom/document_type.zig
- src/browser/dom/processing_instruction.zig
Netsurf's dom_node_is_equal appears to be both unsafe and incorrect. It's unsafe because various node types don't have the dom_node_get_attributes implementation so they default to setting the node attributes to null: https://github.com/lightpanda-io/libdom/blob/master/src/core/node.c#L658
However, it doesn't do a NULL check when comparing them, so it crashes: https://github.com/lightpanda-io/libdom/blob/da8b967905a38455e4f6b75cc9ad2767bae3ccde/src/core/namednodemap.c#L312
Furthermore, specific nodes need to be compared using specific attributes/values.
This PR fixes a WPT crash.
> Implement custom isEqualNode

- src/browser/dom/processing_instruction.zig
When you clone a processing_node via the node_clone_node, or directly via the processing_node copy, you end up in _dom_pi_copy:
https://github.com/lightpanda-io/libdom/blob/da8b967905a38455e4f6b75cc9ad2767bae3ccde/src/core/pi.c#L104
For whatever, reason, the node created here gets a vtable that doesn't seem compatible with how we cast vtables in netsurf.zig. For now, a simple fix is to create a new new and copy the attributes over.
Fixes https://github.com/lightpanda-io/browser/issues/123 and a WPT crash.
> Manually "clone" processing_instruction

- src/browser/dom/html_collection.zig
- src/browser/dom/mutation_observer.zig
- src/browser/url/url.zig
- src/browser/xhr/xhr.zig
- src/cdp/domains/page.zig
Change a few old alloc+memcpy to dupe
Some other smaller cleanups.
> Remove unnecessary cleanup when we know we have an arena

- src/browser/dom/node.zig
- src/browser/netsurf.zig
- src/cdp/testing.zig
This change, in combination with https://github.com/lightpanda-io/libdom/pull/22 fixes a number of crashes when using these functions.
> pass null namespace/prefix to libdom

- src/cdp/domains/page.zig
chromedp client expects to receive Page.frameNavigated before DOM.documentUpdated.
> cdp: dispatch Page.frameNavigated before DOM.documentUpdated

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/target.zig
- src/cdp/testing.zig
It's still generic over the client - we need to assert messages written to and be able to send specific commands, but it's no longer generic over Browser/ Session/Page/etc..
> Make CDP less generic.

- build.zig.zon
- src/runtime/js.zig
- Fixes some locals that were leaking onto the global scope
> Remove global scope

- build.zig.zon
- src/browser/browser.zig
- src/browser/dom/mutation_observer.zig
- src/browser/env.zig
- src/browser/polyfill/fetch.zig
- src/browser/polyfill/polyfill.zig
- src/cdp/cdp.zig
- src/cdp/domains/dom.zig
- src/cdp/domains/page.zig
- src/cdp/domains/runtime.zig
- src/cdp/domains/target.zig
- src/cdp/testing.zig
- src/main.zig
- src/notification.zig
- src/runtime/js.zig
- src/runtime/test_primitive_types.zig
- src/runtime/testing.zig
- src/testing.zig
- src/url.zig
- src/wpt/run.zig
PR does 2 cleanups and 1 hack.
1 - Moves a lot of the `Executor` and `Session` logic/data down to the `Scope` and the `Page`. This provides correct isolation when navigating from page-to-page and minimizes some of the v8 scoping. A Page/Scope now owns the `window` (globla), `session_state` (ooopps, should rename this to `page_state`?) and its own v8.Context.
2 - Moves the inspector out of the `Session` and into the `BrowserContext`. The inspector, it's callback hookup, it's `aux_data` and everything else, is fully managed by the CDP layer. Browser/Session are now inspector-unaware.
3 - To fix the isolated world crash, I force-create the isolated world _before_ the page is created and always shutdown the page before shutting down the isolated world.
(3) is a hack, but I'm still not sure …
> Reorganize v8 contexts and scope

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/target.zig
- src/runtime/js.zig
- src/runtime/testing.zig
- src/testing.zig
- Only the main world page holds a HandleScope and an opened Context
- Isolated Worlds do not hold a HandleScope and the Context is closed by default
- An isolatedWorld context can only be made when there is a page
- v8.context no longer live on the scope allowing the isolated world to be constructed after the page creation.
Note, we should probably:
- rename Executor to World
- rename Scope to Context
- store the HandleScope in the SessionState
- rename the createIsolatedWorld function to something similar to createPage, since the world already exists, adoptPage?, embracePage, assimilatePage? navigatePage, reset/reinitwithPage
[Feel free to merge if approved]
> Share underlying DOM global Window with the isolated World

- src/app.zig
- src/browser/browser.zig
- src/cdp/cdp.zig
- src/main.zig
- src/notification.zig
- src/telemetry/telemetry.zig
Replaces the existing, very specialized Notification with something more general.
Currently, the existing page_navigate and page_navigated have been migrated.
Telemetry's page navigation event now also hooks into these events to generate the telemetry record.
There's a comment on the Notification class that talks about scoping, but...
I initially thought I'd have a global singleton, and it would be really easy to register and dispatch events. But then I realized that wouldn't work. If everything's a global, and CDP is registered for "http_bytes_received", then when Telemetry makes an HTTP request, and the client emits a "http_bytes_received" message, CDP will get those messages.
I realized things needed to be scoped. I thought about introducing a "scope_id", but decided to create a …
> Introduce more general notification capabilities

- src/runtime/loop.zig
cancel on linux was a "real" cancel, but the implementation was unsafe. It took whatever `id` it was given and @ptrFromInt'd it. This is problematic since the `id` is user-supplied with virtually no validation.
Using the existing MacOS canceled lookup seems both easier and safer than trying to validate the cancellation id.
> Change the Linux cancel implementation to match MacOS'

- .github/actions/install/action.yml
- Dockerfile
- build.zig.zon
- src/runtime/js.zig
- src/runtime/test_complex_types.zig
There's ambiguity in mapping due to the flexible nature of JavaScript. Hopefully most types are unambiguous, like a string or a `*parser.Node`.
We need to "probe" each field to see if it's a possible candidate for the JS value. On a perfect match, we stop probing and set the appropriate union field. There are 2 levels of possible matches: candidate and coerce. A "candidate" match has higher precedence. This is necessary because, in JavaScript, a lot of things can be coerced to a lot of other, seemingly wrong, things.
For example, say we have this union:
a: i32,
b: bool,
Field `a` is a perfect match for the value 123. And field b is a coerce match (because, yes, 123 can be coerced to a boolean). So we map it to `a`.
Field `a` is a candidate match for the value 34.2, because float -> int …
> Support union parameters

- src/browser/dom/element.zig
```
RUNS=10 node playwright/cdp.js                               0
Connection to browser on ws://127.0.0.1:9222
..........
total runs 10
total duration (ms) 562
avg run duration (ms) 53
min run duration (ms) 49
max run duration (ms) 74
```
> add Element.matches web api

- src/browser/browser.zig
- src/cdp/cdp.zig
- src/cdp/domains/dom.zig
- src/cdp/domains/page.zig
- src/cdp/domains/target.zig
- src/notification.zig
- src/runtime/js.zig
Polyfills are now loaded into the isolated world
The isolated world is created only when needed and removed and created along with the main page if it exists.
> Isolated polyfill & create world when needed

- src/browser/dom/html_collection.zig
These values are set to undefined, and used (in the item function) before ever being set. Causes crashes in release mode.
> Remove undefined that causes crash

- src/browser/env.zig
- src/runtime/js.zig
- src/runtime/testing.zig
Previously, we were passing our WebAPIs directly as an anonymous tuple. This resulted in Env(T) having an _awful_ name - a name composed of hundreds of classes.
By wrapping the anonymous tuple into a normal struct, the Env now gets a sane name which helps improve stack traces (and profiling, and debugging, ...)
> Improve the debug ergonomics of the Env generic.

- src/browser/browser.zig
- src/browser/dom/dom.zig
- src/browser/dom/element.zig
- src/browser/dom/intersection_observer.zig
- src/browser/netsurf.zig
Implements:
- IntersectionObserver
- IntersectionObserverEntry
- Element.getClientRects
Changed the client's width +1 to make sure all elements are inside. Should we instead start counting from 0?
Notes:
1. We return [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) instead of its parent class DOMRectReadOnly.
1. We call the callback immediately, we do not wait for any event that could cause an intersection change, like scrolling, resizing, DOM modification.
1. We always indicate the root and target element are fully intersecting
> Native IntersectionObserver

- src/cdp/domains/input.zig
Mouse events can be in the middle of a pixel `{x: 1.5, y: 0.5}`
NetSurf Dom or our rendered do not support that and just need the pixel where the event happened so we convert it to an integer when we get the value.
> Subpixel mouse events

- src/runtime/js.zig
NamedFunction is important for displaying good error messages when there's something wrong with the Zig structs we're trying to bind to JS. By making it a normal struct, it's easier and cheaper to pass wherever an @compileError might be needed.
> Change NamedFunction from a generic to a normal struct.

- src/browser/browser.zig
- src/runtime/loop.zig
A loop interval will no longer stop the loop from returning from `run`, and no longer requires mutating event_nb on each iteration.
Re-enable microtask loop, which I accidentally stopped in a previous commit.
> Optimize intervals, and make sure they're probably cleaned up.

- src/browser/css/parser.zig
> "Improve" css selector parsing

- src/browser/browser.zig
- src/runtime/js.zig
The browser has more context than the env about when this should be called. 
Specifically it can be called once per session, whereas, in the env, we can only call it once per context - which could be too often. I was hoping this would improve some of the isolated world performance regression, since this was now being called 2x as often, but it seems to have little impact. I still prefer it in the browser.
> Move call/control of gc_hint to browser.

- src/browser/browser.zig
- src/browser/dom/element.zig
- src/browser/dom/intersection_observer.zig
- src/url.zig
Several issues prevents MouserPressed commands from working:
- URL buffer of 1kb resulted in OutOfMemory error for puppeteer click.js
- of by 1 errors in renderer's pixel location -> rendered now starts at x=0 instead of x=1
- Delay navigation as otherwise the dom tree was deleted during the event causing a crash
> Mouse event fixes

- .github/workflows/build.yml
- .github/workflows/cla.yml
- .github/workflows/e2e-test.yml
- .github/workflows/wpt.yml
- .github/workflows/zig-fmt.yml
- .github/workflows/zig-test.yml
By default the timeout is 6 hours, for most workflows this is much higher than needed.
In cases where we hit infinite loops it may take a while to realize what is going on, by having the workflow fail after a reasonable timeout less time/resources are waisted. The timeout should still be lenient to not be annoying.
For more info see:
[GHA Job Timeout](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)
> Timouts for all GH actions

- src/browser/dom/character_data.zig
- src/browser/dom/document.zig
- src/browser/dom/element.zig
- src/browser/dom/node.zig
Element and CharData both have a before & after function.
Also, changed the existing functions that took a Node but should take a Node or Text, i.e append, prepend and replaceChildren. These functions, along with the new before/after all take a new NodeOrText union.
> Add before and after functions

- src/browser/browser.zig
- src/browser/html/html.zig
- src/browser/html/media_query_list.zig
- src/browser/html/window.zig
- src/runtime/js.zig
- Add dummy MediaQueryList and window.matchMedia
- Execute deferred scripts after non-deferred I realize this doesn't change much, given how we currently load all scripts after the document is parsed, but scripts _could_ depend on execution order.
- Add support for executing the `onload` attribute of <scripts>
I also cleaned up some of the Script code, i.e. removimg `unknown` kind and simply returning a null script, and removing the EmptyBody error and returning a null body string.
> Work on DDG support (but still not working)

- src/browser/dom/element.zig
- src/browser/netsurf.zig
Driven by dom/nodes/attributes.html. However, many issues remain and seem complicated to fix. Some of the remaining issues are documented in https://github.com/lightpanda-io/project/discussions/124
> A few attribute fixes

- src/browser/browser.zig
- src/url.zig
This fixes the issue with URLs being resolved resulting in a weird single slash case. It introduces a `stichUrl` function that basically does what the old resolve was supposed to do.
This was present here and was the cause of the `error.MissingHost`:
```$ zig build run -- fetch   'https://www.reddit.com/r/Zig/comments/1ke7bau/zig_has_great_potential_for_async/'
info(http_client): redirecting to: GET https://www.reddit.com/r/Zig/comments/1ke7bau/zig_has_great_potential_for_async/?rdt=45651
info(browser): GET https://www.reddit.com/r/Zig/comments/1ke7bau/zig_has_great_potential_for_async/?rdt=45651 200
info(browser): fetch https://www.redditstatic.com/shreddit/en-US/icon-97fc6e52.js: 200
info(browser): fetch https://www.redditstatic.com/shreddit/en-US/shell-ff439fbd.js: 200
error(js): …
```
> Fix URL Resolving

- src/browser/browser.zig
- src/cdp/testing.zig
Playwright registers event handlers using Runtime.evaluate in the isolated world before any htmldoc is loaded.
Malloc would fail if netsurf was not initialized. This change initializes the parser on page create which is called when the Page.createTarget. It is ensured that this is called before createIsolatedWorld as createIsolatedWorld requires a main page to be created.
An additional benefit is that it is now symmetric with page removal where the parser is deinited.
_addEventListener (for Window)
eventTargetHasListener
strFromData
dom_string_create
> Init netsurf at page creation

- .github/actions/install/action.yml
- Dockerfile
- build.zig.zon
- src/runtime/js.zig
- src/runtime/test_primitive_types.zig
- src/runtime/testing.zig
```zig
pub fn _returnUint32(_: *const Primitives) Env.TypedArray(u32) {
return .{ .values = &.{ 10, 2444343, 43432432 } };
}
```
> Ability to return typed arrays

- src/browser/xhr/xhr.zig
- src/http/client.zig
- src/main.zig
The idle connection pool is currently sub-optimial, as it only re-uses connections on an exact match. Specifically, it would be nice if a connection could be re-used if the host:port is a match, but the current implementation also requires the blocking mode to match.
So we potentially still need 4x more connections, but in reality, it's probably more like 2x. Most people are only going to be dealing with TLS traffic, so when you connect to lightpanda.io, you'll need 1 connection for the blocking calls and 1 connections for the nonblocking calls.
For plaintext request, it would be simple to share connections between blocking and nonblocking. But for encrypted requests, we need to dig more into tls.zig and figure out how/if a `tls_client` can be converted to <-> from  blocking to …
> add keepalive to http client

- src/browser/dom/element.zig
The closest() method of the Element interface traverses the element and its parents (heading toward the document root) until it finds a node that matches the specified CSS selector.
Returns the closest ancestor Element or itself, which matches the selectors. If there are no such element, null.
Docs: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
> Element closest

- src/browser/browser.zig
This adds a `module_map` to the `Page` that prevents circular dependencies from entering a fetch loop. It uses the full path (obtained with the `URL.stitch`) as the key.
> Page Module Map

- src/browser/encoding/text_encoder.zig
- src/browser/env.zig
> WIP implement TextEncoder

- src/browser/browser.zig
- src/browser/html/html.zig
- src/browser/html/performance.zig
- src/browser/html/window.zig
- src/cdp/testing.zig
- src/testing.zig
Initial implementation of 2 interfaces of performance
https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
many still TODO
Performance implementation as part of Window, [WorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope) not implemented.
These APIs are implemented as part of making Playwright click work.
> Performance now

- src/browser/html/window.zig
Depends on: https://github.com/lightpanda-io/browser/pull/636
Not sure how I feel about immediately executing the callback.
Used in Playwright click
> window.requestAnimationFrame

- src/browser/browser.zig
These tags should not be loaded as we support ES modules.
> Don't load script tags with the nomodule attribute

- src/browser/dom/element.zig
- src/browser/html/window.zig
- src/cdp/domains/dom.zig
- `element.scrollIntoViewIfNeeded`
- `DOM.scrollIntoViewIfNeeded`
- `DOM.getContentQuads`
- `innerHeight`
- `innerWidth`
> scrollIntoViewIfNeeded, getContentQuads, innerWidth/Heigh

- src/app.zig
- src/browser/browser.zig
- src/browser/xhr/xhr.zig
- src/http/client.zig
- src/main.zig
There are at least two types of proxies we should support, relaying and MITM (I don't know what it's actually supposed to be called).
This adds support for MITM, which means that our HTTP client does a normal HTTP request to the proxy server, but the request path is the full URL. The upstream proxy then issues its own HTTP request to the destination. The benefit of this approach is that the proxy can easily modify the request/response, which is the behavior I currently need.
> add direct http proxy support

- src/runtime/js.zig
When calling a Zig function from JS fails due to a parameter type error, log.debug information about the function and parameters.
> Make Callback.printFunc public

- src/browser/dom/event_target.zig
addEventListener can take a boolean (capture, already supported) or an object of options. This adds union support for the two, but only supports the `capture` field of the options object.
Supporting the other fields (once, passive & signal) is possibly another non-trivial change to netsurf. cc @krichprollsch
> Support the capture field of the addEventListener option

- src/browser/dom/html_collection.zig
- src/browser/dom/nodelist.zig
- src/runtime/js.zig
1 - Named properties should not be enumerable
2 - Empty key should always result in a null/undefined (depending on the API)
even if there's an element with an empty id/name
To address the first issue, we now require PropertyAttributes to be specified when setting an object's value.
> Fix HTMLCollection named property issues

- .github/actions/install/action.yml
- Dockerfile
- build.zig.zon
- src/browser/dom/html_collection.zig
- src/browser/dom/node.zig
- src/browser/html/document.zig
- src/runtime/js.zig
Capture its unique properties:
1- instances are falsy, and
2- instance can be called as a function
The behavior is used for browser detection (i.e. duckduckgo treats us as a legacy browser because we document.all != false)
> Rework HTMLAllCollection

- src/browser/browser.zig
- src/browser/session.zig
- src/cdp/cdp.zig
Some data has to exist specifically for the navigation of one page to another. For example, if a hyperlink is clicked, the URL begins its life with the original page, but is transferred to the new page. The page_arena cannot be used for such data.
It's possible to use the session_arena, but it's lifetime is much longer and, given enough navigation, could accumulate a lot of memory.
The new transfer_arena exists within the session, but only exists until the next navigation.
While currently only used for the navigation URL, the main goal here is to have a place to put the request body on form submission, which has a lifetime similar to a click url.
While I'm at it, I promoted the existing session arena and the new transfer arena to the browser, allowing better memory re-use between …
> Introduce a "transfer_arena"

- build.zig.zon
- src/browser/page.zig
- src/runtime/js.zig
depends on https://github.com/lightpanda-io/zig-v8-fork/pull/71
fix #654
> module: report module's evaluation error

- src/browser/dom/comment.zig
- src/browser/dom/document.zig
- src/browser/dom/document_fragment.zig
- src/browser/dom/intersection_observer.zig
- src/browser/dom/processing_instruction.zig
- src/browser/dom/text.zig
- src/browser/env.zig
- src/browser/page.zig
- src/main_wpt.zig
- src/testing.zig
document was stored both in Window as well as the SessionState.
Since Window is not in the SessionState we can duplicate and no longer need to keep them in sync.
Convenience accessor was not added as we have enough indirection.
```zig
pub fn document(self: *SessionState) ?*parser.Document {
return self.window.document;
}
```
> Deduplicate document

- src/browser/env.zig
- src/browser/html/document.zig
- src/browser/netsurf.zig
- src/browser/page.zig
This feature is implemented by embedding the Zig instance into a libdom node, allowing us to extend the functionality of libdom without having to change it. This was made possible by https://github.com/lightpanda-io/libdom/pull/26
> Add document.readyState

- src/browser/dom/element.zig
- src/browser/dom/intersection_observer.zig
- src/browser/dom/node.zig
- src/browser/html/document.zig
- src/browser/html/window.zig
- src/browser/netsurf.zig
- src/browser/renderer.zig
- src/cdp/domains/dom.zig
Depends on: https://github.com/lightpanda-io/browser/pull/638
Implements the last 2 web apis for Playwright click:
- `Document.elementFromPoint`
- `Document.elementsFromPoint`
https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint
Reimplemented:
- `Node.getRootNode` also in netsurf
- `Element.getBoundingClientRect`
- `Element.getClientRects`
> elementFromPoint + elementsFromPoint

- src/http/client.zig
Compliments https://github.com/lightpanda-io/browser/pull/601 which added this behavior to the SyncHandler.
> Add support for gzip responses in AsyncHandler

- build.zig
- src/browser/page.zig
- src/main.zig
- src/runtime/js.zig
- src/telemetry/lightpanda.zig
1 - Add a log_level build option to control the default log level from
the build (e.g. -Dlog_level=debug). Defaults to info
2 - Add a new boolean log_unknown_properties build option to enable
logging unknown properties. Defautls to false.
3 - Remove the log debug for script eval - this can be a huge value
(i.e. hundreds of KB), which makes the debug log unusable IMO.
> Tweak debug logging

- src/browser/dom/comment.zig
- src/browser/dom/document.zig
- src/browser/dom/document_fragment.zig
- src/browser/dom/element.zig
- src/browser/dom/intersection_observer.zig
- src/browser/dom/processing_instruction.zig
- src/browser/dom/text.zig
- src/browser/html/document.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/cdp/domains/dom.zig
- src/cdp/domains/target.zig
- src/cdp/testing.zig
- src/main_wpt.zig
- src/testing.zig
- src/url.zig
Builds on loading document for about:blank: https://github.com/lightpanda-io/browser/pull/668
Since half the code of that PR is removed again, might as well just review this one.
This make the window.document not optional, and sets it to about:blank by default.
> Not optional document

- src/browser/dom/mutation_observer.zig
- src/browser/xhr/xhr.zig
- src/http/client.zig
- src/runtime/js.zig
Add destructor to XHR to abort any inflight requests.
> Allow webapis to register a destructor to do cleanup on scope (page) end

- src/cdp/domains/dom.zig
- `dom.querySelector`
- `dom.querySelectorAll`
For use in chromedp/click
> dom.querySelector

- src/runtime/js.zig
Caller is a transient object that exists only for calling Zig functions from JS. But jsValueToZig is more generally useful and can be used outside of an explicit JS call. The scope is a better place for these as it's generally referenced already by any code that would need to map values (i.e. a Callback).
> Move jsValueToZig from Caller to the Scope

- src/server.zig
Playwright increased the size of their intermediate JS layer, which no longer fit our MAX_MESSAGE_SIZE.
This fixes: https://github.com/lightpanda-io/demo/pull/41
fix #676
> Increase MAX_MESSAGE_SIZE

- src/browser/session.zig
- src/cdp/cdp.zig
- src/cdp/domains/dom.zig
- src/cdp/domains/page.zig
- src/runtime/js.zig
- src/runtime/testing.zig
- src/testing.zig
Renaming Executor to ExecutionWorld, to reduce the number of concepts that we need to learn.
ExecutionWorld closely models a JS World as recognized below:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld
https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/bindings/core/v8/V8BindingDesign.md#World
I see no issue with variables being called executor.
> Rename to ExecutionWorld

- .github/actions/install/action.yml
- Dockerfile
- build.zig
- build.zig.zon
This will fallback to the current directory structure (without the OS in the path), so that it shouldn't break anyone's development environment. Next time we do a big upgrade that requires everyone to rebuild-v8, we can remove the fallback code.
> include OS in libc_v8 lib path

- src/browser/html/elements.zig
- src/browser/netsurf.zig
Related to https://github.com/lightpanda-io/project/issues/115#issue-3039251901
`fetch 'https://www.google.com/search?q=browser+headless'`
Constructors + all non deprecated properties implemented by netsurf
Q: Do we want the deprecated ones as well, or do they just take up memory?
> new Image constructor

- .github/workflows/e2e-test.yml
- src/browser/env.zig
- src/browser/page.zig
- src/browser/xhr/xhr.zig
- src/cdp/cdp.zig
- src/cdp/domains/network.zig
- src/cdp/domains/page.zig
- src/http/client.zig
- src/notification.zig
- src/testing.zig
- Add 2 internal notifications 1 - http_request_start 2 - http_request_complete
- When Network.enable CDP message is received, browser context registers for these 2 events (when Network.disable is called, it unregisters)
- On http_request_start, CDP will emit a Network.requestWillBeSent message. This _does not_ include all the fields, but what we have appears to be enough for puppeteer.waitForNetworkIdle.
- On http_request_complete, CDP will emit a Network.responseReceived message. This _does not_ include all the fields, bu what we have appears to be enough for puppeteer.waitForNetworkIdle.
We currently don't emit any other new events, including any network-specific lifecycleEvent (i.e. Chrome will emit an networkIdle and networkAlmostIdle).
To support this, the following other things …
> HTTP request notification

- src/browser/netsurf.zig
- src/browser/page.zig
Once https://github.com/lightpanda-io/libdom/pull/27 is merged, can update this PR with the new commit for libdom.
> Load dynamically added <script> tags

- src/browser/html/elements.zig
- src/runtime/js.zig
HTMLImageElement is the correct class name. However, it has a "legacy factory": Image (i.e. new Image()).
> Fix HTMLImageElement

- src/browser/html/elements.zig
- src/browser/page.zig
Add support for onerror for static and dynamic scripts.
Make script type checking case insensitive.
> Execute onload for dynamic script

- src/browser/html/document.zig
- src/browser/html/location.zig
- src/browser/html/window.zig
- src/browser/page.zig
I'm not sure that _any_ location instance should be able to change the page URL. But you can't create a new location (i.e. new Location() isn't valid), and the only two ways I know of are via `window.location` and `document.location` both of which _should_ alter the location of the window/document.
> Implement location.reload(), location.assign() and location setter

- src/browser/html/document.zig
- src/browser/html/form.zig
- src/browser/html/location.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/browser/session.zig
- src/browser/xhr/form_data.zig
- src/cdp/domains/page.zig
- src/url.zig
This builds on top of https://github.com/lightpanda-io/browser/pull/715
Supports GET and POST, but only supports the default encoding type, i.e. `application/x-www-form-urlencoded`.  Currently can only be triggered by the `sumbit()` JavaScript function. Extending it to button click is the next step and should be a relatively simple addition.
> Form submit

- src/browser/page.zig
DDG will sometimes return a 202 for its result javascript, meaning it isn't ready and the rest of the JS will then handle that case. It's weird, but there's no reason for us to abort on a 2xx code.
> Allow any 2xx status code for scripts

- build.zig
- src/browser/console/console.zig
- src/browser/dom/element.zig
- src/browser/dom/intersection_observer.zig
- src/browser/dom/mutation_observer.zig
- src/browser/dom/node.zig
- src/browser/dom/nodelist.zig
- src/browser/dom/token_list.zig
- src/browser/events/event.zig
- src/browser/html/document.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/browser/polyfill/polyfill.zig
- src/browser/session.zig
- src/browser/storage/cookie.zig
- src/browser/xhr/form_data.zig
- src/browser/xhr/xhr.zig
- src/http/client.zig
- src/log.zig
- src/main.zig
- src/notification.zig
- src/runtime/js.zig
- src/server.zig
This is meant to significantly improve the logging for implementation work, by reducing noise and increasing details.
See the 2 commit messages for details.
> Improved logging

- src/browser/dom/event_target.zig
- src/runtime/js.zig
Probably need to add this in more places.
> Guard against null object when trying to fetch a function

- src/browser/page.zig
- src/browser/url/url.zig
- src/url.zig
url, base were being joined in the wrong order. Switch to using URL.stitch if a base is given.
> Fix url constructor

- src/browser/console/console.zig
- src/runtime/js.zig
If you look at the specification for `console` [1], you'll note that it's a namespace, not an interface (like most things). Furthermore, MDN lists its methods as "static".
But it's a pretty weird namespace IMO, because some of its "functions", like `count` can have state associated with them.
This causes some problems with our current implementation. Something like:
```
[1].forEach(console.log)
```
Fails, since `this` isn't our window-attached Console instance.
This commit introducing a new `static_XYZ` naming convention which does not have the class/Self as a receiver:
```
pub fn static_log(values: []JsObject, page: *Page) !void {
```
This turns Console into a namespace for these specific functions, while still being used normally for those functions that require state.
We could infer …
> Poor support for functions/namespaces.

- flake.lock
- flake.nix
This updates the `flake.lock` and also updates it to use version `25.05`.
> Bump Nixpkgs to 25.05

- src/browser/html/elements.zig
- src/browser/netsurf.zig
- src/url.zig
Depends on: https://github.com/lightpanda-io/libdom/pull/28
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
Properties that are implemented by Netsurf, not deprecated, and not inherited from HTMLElement.
With these we probable have enough examples to make a generic implementation, for that note that there are some special cases:
- Some netsurf properties are deprecated
- Netsurf does not support all properties
- Some properties are inherited through the prototype chain
- Some properties have default values if the netsurf says null or the unsigned version of -1
- The initial value and the default value do not need to be the same. init -1 default 0 for example.
- The set and get types may be different get may return -1 `i32`, but set must be positive `u32`
- Some specific …
> Input element properties

- src/browser/dom/event_target.zig
- src/browser/events/custom_event.zig
- src/browser/events/event.zig
- src/browser/xhr/progress_event.zig
- src/runtime/generate.zig
On page load, emitted by the page, the target is the window, but it's improperly cast since the pointer is actually `window.base`. This is going to be a problem in general for any Zig type dispatched as a target, but the Window one is the most obvious and the easiest to fix. If this issue comes up with other types, we'll need to come up with a more robust solution.
> Fix crash when event target is the window.

- src/browser/xhr/xhr.zig
- src/http/client.zig
Async HTTP request work by emitting a "Progress" object to a callback. This object has a "done" flag which, when `true`, indicates that all data has been emitting and no future "Progress" objects will be sent.
Callers like XHR buffer the response and wait for "done = true" to then process the request.
The HTTP client relies on two important object pools: the connection and the state (with all the buffers for reading/writing).
In its current implementation, the async flow does not release these pooled objects until the final callback has returned. At best, this is inefficient: we're keeping the connection and state objects checked out for longer than they have to be. At worse, it can lead to a deadlock. If the calling code issues a new request when done == true, we'll eventually run out of …
> Optimize the lifecycle of async requests

- src/browser/html/window.zig
This is often called in a tight loop (the callback to requestAnimation typically calls requestAnimation).
As-is, it can result in the browser locking due to the `requestAnimation` callback calling `requestAnimation`. (I can reproduce this blocking in some cases. I'm not sure why it _doesn't_ always block if it calls itself.).
Instead, we can treat it like a setTimeout with a short delay (5ms ?). This has the added benefit of making it cancelable, FWIW.
> Delay requestAnimation

- src/browser/key_value.zig
- src/browser/url/url.zig
- src/runtime/js.zig
This adds support for:
```
new URLSearchParams({over: 9000});
```
The spec says that any thing that produces/iterates a sequence of string pairs is valid. By using the lower-level JsObject, this hopefully takes care of the most common cases. But I don't think it's complete, and I don't think we currently capture enough data to make this work. There's no way for the JS runtime to know if a value (say, a netsurf instance, or even a Zig instance) provides an string=>string iterator.
> URLSearchParam constructor support for object initialization

- src/app.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/browser/session.zig
- src/browser/xhr/xhr.zig
- src/cdp/domains/input.zig
- src/cdp/domains/target.zig
- src/http/client.zig
- src/runtime/loop.zig
This is a more complicated one. It's depends on both  https://github.com/lightpanda-io/browser/pull/765 and https://github.com/lightpanda-io/browser/pull/766
TL;DR. The async HTTP client can block and, when it does block, the entire browser freezes. The blocking comes from waiting on the state pool's condition variable. Solving this means _getting_ the *Request instance itself has to be asynchronous. So, in XHR, instead of:
```zig
self._request = page.http_client.async(.GET, url, &self, onData)
...
fn onData(ctx: *anyopaque, data: []const u8) !void {...}
```
We need to do something like this (2 steps)
```zig
page.http_client.async(.GET, URL, &self, requestReady);
...
fn requestReady(ctx: *anyopaque, request: *Request) !void {...}
self: *XHR = @ptrCast(ctx);
self.request = request; …
```
> Unblock async http request

- src/browser/page.zig
- src/browser/xhr/xhr.zig
- src/cdp/cdp.zig
- src/cdp/domains/network.zig
- src/http/client.zig
- src/notification.zig
- src/runtime/loop.zig
CDP translate this into a Network.loadingFailed. This is necessary to make sure every Network.requestWillBeSent is paired with either a Network.loadingFailed or a Network.responseReceived.
> Emit http_request_fail notification

- src/browser/dom/document.zig
- src/browser/netsurf.zig
- src/browser/page.zig
- src/browser/xhr/form_data.zig
- src/cdp/domains/input.zig
Support CDP's Input.dispatchKeyEvent and DOM key events. Currently only keydown is supported and expects every key to be a displayable character.
It turns out that manipulating the DOM via key events isn't great because the behavior really depends on the cursor. So, to do this more accurately, we'd have to introduce some concept of a cursor.
Personally, I don't think we'll run into many pages that are purposefully using keyboard events. But driver (puppeteer/playwright) scripts might be another issue.
> Add basic support for key events

- src/runtime/loop.zig
Fixes the DDG result regression.
In https://github.com/lightpanda-io/browser/pull/767 I tried to call loop.run from within a loop.run (spoiler, it didn't work), in order to make sure aborted connections were properly cleaned up before starting a new navigation. That resulted in having loop.run no longer wait for timeouts for fear of having to wait on a long timeout. The ended up breaking page.wait (used in the fetch command).
This commit brings back the original behavior where loop.run() waits for all completions. Which is now safe to do since the nested loop.run() call has been removed.
> Fix loop run (Page.wait)

- src/browser/page.zig
- src/browser/session.zig
- src/browser/xhr/xhr.zig
- src/cdp/domains/target.zig
- src/http/client.zig
- src/runtime/loop.zig
The mix of sync and async HTTP requests requires care to avoid deadlocks. Previously, it was possible for async requests to use up all available HTTP state objects duration a navigation flow (either directly, or via an internal redirect (e.g. click, submit, ...)). This would block the navigation, which, because everything is single thread, would block the I/O loop, resulting in a deadlock.
The correct solution seems to be to remove all synchronous I/O. And I tried to do that, but I ran into a wall with module-loading, which is initiated from V8. V8 says "give me the source for this module", and I don't see a great way to tell it: wait a bit.
So I went back to trying to make this work with the hybrid model, despite last weeks failures to get it to work. I changed two things:
1 - The http …
> Rework internal navigation to prevent deadlocking

- src/browser/html/elements.zig
- src/cdp/domains/network.zig
- src/cdp/domains/page.zig
This is one of the ways that puppeteer knows that navigation happened and is needed to support `waitForNavigation` which compares the existing loader-id with the new one, so it has to change.
Also, fix a crash that could happen if CDP disconnects while connections are being aborted.
> Internal navigation should change the CDP loader-id

- src/browser/xhr/form_data.zig
Libdom's formGetCollection doesn't work (like I would expect) for dynamically added elements.
For example, given:
```
let el = document.createElement('input');
document.getElementsByTagName('form')[0].append(el);
```
(and assume the page has a form), I'd expect `el.form` to be equal to the form the input was added to. Instead, it's null. This is a problem given that `dom_html_form_element_get_elements` uses the element's `form` attribute to "collect" the elements.
This uses our existing querySelector to find the form elements.
> Use css.querySelectorAll to find form elements

- src/browser/css/parser.zig
- src/browser/css/selector.zig
- src/runtime/js.zig
Probing a union match for an possible value should rarely hard-fail. Instead, it should return an .{.invalid = {}} response to let the prober decide how to proceed. This fixes a hard-fail when a JS value fails to probe as an array.
Also, add :modal pseudo-class.
(both issues came up looking at github integration)
> Fix non-probing of union array failure

- src/browser/page.zig
- src/runtime/js.zig
This was previously being set back to null before it was actually needed.
Also, added a more logs / log details.
> Fixes the scoping of page.current_script

- src/cdp/cdp.zig
- src/cdp/domains/target.zig
Currently we rely on there existing only 1 browser context. We just need to make sure that we set it back after the session ends
Additional:
Should we rename `--http-proxy` to `--proxy-server` to align with chromium?
> browser context proxyServer

- src/browser/html/html.zig
- src/browser/html/screen.zig
- src/browser/html/window.zig
This adds the `Screen` and `ScreenOrientation` WebAPIs to the Window.
> add Screen and ScreenOrientation

- src/browser/cssom/css_rule.zig
- src/browser/cssom/css_rule_list.zig
- src/browser/cssom/css_style_declaration.zig
- src/browser/cssom/css_stylesheet.zig
- src/browser/cssom/cssom.zig
- src/browser/cssom/stylesheet.zig
- src/browser/env.zig
- src/cdp/cdp.zig
- src/cdp/domains/target.zig
This is a super barebones CSSStyleSheet, mostly for just resolving various Custom Elements complaining about a lack of the CSSStyleSheet interface.
A lot of functionality is not implemented but it seems to allow more components to load on the Reddit example.
> Minimal CSSStyleSheet

- src/browser/page.zig
- src/runtime/js.zig
When V8 calls the ResolveModuleCallback that we give it, it passes the specifier which is essentially the string given to `from`:
```
import {x} from './blah.js';
```
We were taking that specifier and giving it to the page. The page knew the currently executing script, an thus could resolve the full URL. Given the full URL, it could either return the JS content from its module cache or fetch the source.
At best though, this isn't efficient. If two files import the same module, yes we cache the src, but we still ask v8 to re-compile it. At worse, it crashes due to resource exhaustion in the case of cyclical dependencies.
ResolveModuleCallback should instead detect that it has already loaded the module and return the previously loaded module. Essentially, we shouldn't be caching the …
> Fix module loading

- src/http/client.zig
Add a similar behavior than curl which sends an `Accept: */*` for all requests.
Chrome sends an  `Accept: */*` for xhr request and `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7` for the first request but this last one seems a bit bloated.
> http: send an Accept: */* header

- src/browser/dom/dom.zig
- src/browser/dom/performance.zig
- src/runtime/js.zig
This adds the `PerformanceEntry` and `PerformanceMark` interfaces. This also adds the ability to return enums as long as they have a `toString()` in `js.zig`.
> add PerformanceEntry and PerformanceMark

- src/browser/css/css.zig
- src/browser/env.zig
- src/browser/html/window.zig
This adds in a super minimal `CSS` utility interface. It also modifies the `js.zig` and allows for utility interfaces (Interfaces that contain static elements but can't be constructed) to work.
> add CSS utility interface

- src/browser/crypto/crypto.zig
This is a simple fix that just returns the random values from `crypto.getRandomValues()`. This is needed to get any assets that use uuidjs to work (including Reddit's polyfill).
> Return Random Array from crypto.GetRandomValues

- src/browser/crypto/crypto.zig
- src/browser/css/css.zig
An empty struct will share the same address as its sibling (1) which will cause an collision in the identity map.
(1) - This depends on Zig's non-guaranteed layout, so the collision might not be with its sibling, but rather some other [seemingly random] field.
> We cannot have empty Zig structs mapping to JS instances

- src/browser/crypto/crypto.zig
- src/runtime/js.zig
Crypto.getRandomValues should mutate the given parameter as well as return the value. This return value must be the same (JsObject) as the input parameter.
There might be more magical ways to solve this, but I opted for both the simplest and most flexible: adding a `toZig` function to JsObject which does what js.zig does internally when mapping js values to Zig (and, of course, it uses the same code).
This allows a caller to receive a JsObject (not too common, but we already do that in a few places) and return that same JsObject (again, not too common, but we do have support for returning JsObject directly already). With the main addition that the JsObjet can now be turned into a Zig type by the caller.
> Crypto.getRandomValues consistency

- build.zig.zon
- src/browser/mime.zig
- src/http/client.zig
Was seeing pretty frequent TLS errors on reddit. I think I had the wrong max TLS record size, but figured this was an opportunity to upgrade tls.zig, which has seen quite a few changes since our last upgrade.
Specifically, the nonblocking TLS logic has been split into two structs: one for handshaking, and then another to be used to encrypt/decrypt after the h andshake is complete. The biggest impact here is with respect to keepalive, since what we want to keepalive is the connection post-handshake, but we don't have this object until much later.
There was also some general API changes, with respect to state and partially encrypted/decrypted data which we must now maintain.
> Upgrade tlz.zig to latest version

- src/browser/console/console.zig
- src/browser/dom/event_target.zig
- src/browser/events/event.zig
- src/browser/html/AbortController.zig
- src/browser/html/html.zig
- src/browser/netsurf.zig
- src/runtime/js.zig
Missing the [AbortSignal.any()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static) API.
This API is superficially simple, but required a number of deeper changes.
1 - The poor support for namespace/static functions introduced in https://github.com/lightpanda-io/browser/pull/749 has been improved. Static functions, like `AbortSignal.timeout`, are now correctly supported. 
I still think the `console` behavior is weird, but it's now implemented as a receiver-less method (which is now supported for all methods). Possibly still not correct, but at least it's simpler and and better aligned with how we structure our code.
2 - Like the `Window` before, this introduces an EventTarget which is not a libdom node, an AbortSignal. Unlike `Window`, this isn't a singleton and can't …
> Abort controller

- src/browser/mime.zig
- src/browser/page.zig
When using a non-html document through CDP, you still want to be able to take actions on a DOM tree.
Chrome builds a pseudo DOM tree for non-html webpages.
We display the content in a `<pre>` tag for well known content type and an empty document for others.
> create a DOM tree for non-html files

- src/http/client.zig
In a separate branch atm as it wasn't always clear what the expected meaning of _secure was in different places.
Mainly in: `fn get(self: *ConnectionManager`
> secure changes

- build.zig.zon
- src/runtime/js.zig
Don't error on JSON.stringify failure (likely caused by circular reference).
In debug mode, try to print [slightly] more meaningful value representation when default serialization results in [object Object].
> Improve JS value printing

- build.zig.zon
- src/http/client.zig
Depends on https://github.com/ianic/tls.zig/pull/14
> TLS for CONNECT proxy 

- src/browser/html/document.zig
Not only does this ensure compatibility with browsers, it doesn't crash when the value is NaN of Infinity.
> Rely on js.zig for float->int translation

- src/browser/dom/attribute.zig
- src/browser/dom/namednodemap.zig
Only when setAttribute is called directly on the element, does libdom raise a `DOMAttrModified` event (which MutationObserver uses).
From what I can tell, libdom's element set attribute _does_ rely on the underlying attribute set value, so the behavior should be pretty close, it just does extra things on top of that.
> Attribute.set_value uses element, if possible

- src/browser/html/document.zig
- src/browser/netsurf.zig
Currently seems to always return null. Doesn't seem to be a way in libdom to change this. The property is deprecated, and MDN recommends using location.host instead, so change document.get_domain to wrap location.host.
> Fix document.domain

- src/browser/dom/event_target.zig
- src/browser/netsurf.zig
Depends on: https://github.com/lightpanda-io/libdom/pull/30
> Event target internal type

- src/browser/css/parser.zig
- src/browser/css/selector.zig
This adds very basic support for the visible CSS pseudoclass. It just assumes that everything on the page is visible.
> Visible Psuedoclass

- src/browser/dom/element.zig
- src/browser/netsurf.zig
I couldn't find where the behavior is described. AND, browsers seem to behave differently depending on the state of the page (blank document vs actual page).
Still, some sites use innerHTML to load <script> tags, and, in libdom at least, these are created in the implicit head. We cannot just copy the body nodes. To keep it simple, I now copy all head and body elements.
> Setting innerHTML now captures head elements

- src/browser/dom/document.zig
- src/browser/dom/dom.zig
- src/browser/dom/node_filter.zig
- src/browser/dom/node_iterator.zig
- src/browser/dom/tree_walker.zig
- src/browser/html/window.zig
https://developer.mozilla.org/en-US/docs/Web/API/Document/createNodeIterator
Does not reuse the TreeWalker implementation as there are several subtle differences
TreeWalker is likely not handling its edges cases correctly, those are not addressed in this PR except fixing, `get_filter()`, `_previous_node()` going beyond the root and functions returning `*parser.Node` instead of `Node.Union`
> NodeIterator

- src/http/client.zig
XHR requests to https (which is most XHR requests) currently don't work with the implementation proxy because of this.
> Fix async https requests over a http forward proxy

- src/browser/dom/element.zig
- src/browser/dump.zig
- src/browser/page.zig
- src/browser/xmlserializer/xmlserializer.zig
- src/main.zig
Currently, fetch --dump includes <script> tag (either inline or with src). I don't know what use-case this is the desired behavior. Excluding them, via the new --noscript option has benefit that if you --dump --noscript and open the resulting page in the browser, you don't re-execute JavaScript, which is likely to break the page.
For example, opening a --dump of github makes it look like the page is broken because it re-executes JavaScript that isn't meant to be re-executed.
Similarly, opening a --dump in a browser might execute JavaScript that lightpanda browser failed to execute, making it looks like it worked better than it did.
> Add a --noscript option to "improve" --dump

- src/browser/dom/Animation.zig
- src/browser/dom/dom.zig
- src/browser/dom/element.zig
- src/browser/env.zig
- src/runtime/js.zig
These are dummy implementations, but they do expose the ready and finished promise, and do resolve the finished promise, so it should unblock basic cases.
> Add Element.animate and Animation

- src/url.zig
Also handle ./ anywhere in the path.
> Rework URL.stitch, handle ../ (for yahoo)

- build.zig.zon
- src/browser/encoding/TextDecoder.zig
- src/runtime/js.zig
Depends on https://github.com/lightpanda-io/zig-v8-fork/pull/86
Built ontop of https://github.com/lightpanda-io/browser/pull/906 just because this is the feature that uses it.
> Map ArrayBuffer and ArrayBufferView to u8.

- src/browser/netsurf.zig
- src/browser/page.zig
Depends on https://github.com/lightpanda-io/libdom/pull/31
> Prevent double-execution of script tags.

- src/browser/dom/document.zig
- src/browser/dom/document_fragment.zig
- src/browser/dom/element.zig
- src/browser/dom/html_collection.zig
- src/browser/html/document.zig
- src/browser/html/elements.zig
- src/browser/html/select.zig
- src/browser/netsurf.zig
Add HTMLOptionsCollection and enhance HTMLOptionElement API.
Amazon.
> Implement select.options

- src/browser/xhr/event_target.zig
This supersedes #912. It fixes the same behavior but in a more proper way, by allowing and handling null event listeners that are expected to clear the callback.
> Handle Null Event Listener

- src/runtime/js.zig
- src/runtime/test_primitive_types.zig
I get the crash with youtube.com
> Fix crashes with empty array

- src/browser/dom/element.zig
- src/browser/dom/shadow_root.zig
- src/browser/events/event.zig
- src/browser/netsurf.zig
Adds event.composedPath()
This depends on https://github.com/lightpanda-io/libdom/pull/34
> Add ShadowRoot get/set innerHTML

- src/browser/dom/node.zig
The previous implementation just checked if a node had a parent. But it should check the node has a document ancestor:
```
const d1 = document.createElement('div');
document.createElement('div').appendChild(d1);
d1.isConnected
```
should be `false`.
In addition to this fix, also added support for DocumentFragments which are part of the ShadowRoot. This, like events, is one of those apis that DOES break the ShadowRoot isolation.
> Fix Node.isConnected

- src/browser/ScriptManager.zig
- src/browser/browser.zig
- src/browser/page.zig
- src/browser/xhr/xhr.zig
- src/cdp/cdp.zig
- src/cdp/domains/fetch.zig
- src/cdp/domains/network.zig
- src/http/Client.zig
- src/http/Http.zig
- src/notification.zig
Depends on: https://github.com/lightpanda-io/browser/pull/922
Also reenables: `http_request_start`
TODO:
Example playwright fragment:
```js
const page = await context.newPage();
await page.route('**/*', (route, request) => {
console.log(`Request ROUTE: ${request.method()} ${request.url()}`);
route.continue({url: "http://lightpanda.io/", method: "GET"});// or route.abort();
});
await page.goto('/campfire-commerce/');
```
> request interception

- src/http/Client.zig
- src/http/Http.zig
Enabling Curl cookie engine brings advantages:
* handle cookies during a redirection: when a srv redirects including cookies, curl sends back the cookies correctly during the next request
* ~benefit curl's cookie parsing: we now use curl's lib to parse cookies instead of parsing them from headers manually~ still use our own parsing
> enable curl cookie engine

- src/url.zig
> Fix network-path reference stitching

- src/http/Client.zig
- src/http/Http.zig
This PR fixes the cookies handling on redirection.
The original problem was:
> It seems to work correctly except one case: if you set manually a cookie (A=A) and the server sets one with the same name (A=B) and it redirects, then the redirect request will send the cookie twice with the 2 values (eg. Cookie: A=A; A=B).
This PR de-activate the Curl's cookie engine.
We now set cookies manually in redirection to ensure only once `Cookie:` is set.
relates with #940
> handle cookies on redirection manually

- src/browser/dom/exceptions.zig
- src/browser/dom/node.zig
- src/browser/dom/range.zig
- src/main_wpt.zig
- src/runtime/js.zig
Should fix a good chunk (~20K I think) of the recently broken WPT tests.
> Improve correctness of Node.compareDocumentPosition and Range api.

- src/browser/css/libdom_test.zig
- src/browser/css/match_test.zig
- src/browser/css/parser.zig
- src/browser/dom/element.zig
- src/browser/dom/shadow_root.zig
- src/browser/storage/cookie.zig
- src/browser/url/url.zig
- src/browser/xmlserializer/xmlserializer.zig
Very minor, but the more we can do upfront to align the code for Zig 0.15, the better.
> Replace all std.ArrayList with std.ArrayListUnmanaged

- src/cdp/cdp.zig
- src/cdp/domains/network.zig
- src/http/Client.zig
- src/notification.zig
Add response_data event, CDP now captures the full body so that it can respond to the Network.getResponseBody. This isn't memory efficient, but I don't see another way to do it. At least this way, it's only capturing/storing every response body when (a) CDP is used and (b) Network.enabled is called. That is, as opposed to baking this into Http/Client.zig, which would force the memory consumption for all use-cases.
There's arguably some optimizations we could make for XHR requests, which also dupe/own the response. As of now, the response is dupe'd separately for CDP and XHR.
> Implement Network.getResponseBody

- src/browser/dom/range.zig
Also rename start_container and end_container to start_node and end_node.
> Add Range.compareBoundaryPoints

- src/cdp/domains/network.zig
chromedb doesn't support duplicate header names. Although servers _will_ send this (e.g. Cache-Control: public\r\nCache-Control: max-age=60\r\n), Chrome seems to join them with a "\n". So we do the same.
A note on curl_easy_nextheader, which this code ultimately uses to iterate and collect the headers. The documentation says:
Applications must copy the data if they want it to survive subsequent API
calls or the life-time of the easy handle.
As-is, I'd understand this to mean that a given header name/value is only valid until any API call, including another call to curl_easy_nextheader. So, from this comment, we _should_ be duping the name/value. But we don't. Why? Because, despite the note in the documentation, this doesn't appear to be how it actually works, nor does it really make …
> Normalize CDP response headers

- src/browser/ScriptManager.zig
Some sites have a lot of text/template or application/json, and it just adds noise to the logs.
> Removes the log for unknown script tags

- src/browser/ScriptManager.zig
- src/browser/events/event.zig
- src/browser/html/elements.zig
- src/browser/page.zig
This should load the "src.js":
```
const s = document.createElement('script');
document.getElementsByTagName('body')[0].appendChild(s);
s.src = "src.js"
```
Notice that src is set AFTER the element is added to the DOM. This PR enables the above, by
1 - skipping dynamically added scripts which don't have a src 2 - trying to load a script whenever `set_src` is called.
(2) is safe because the ScriptManager already prevents scripts from being processed multiple times.
Additionally, not only can the src be set after the script is added to the DOM, but onload and onerror can be set after the src:
```
s.src = "src.js"
s.onload = ...;
s.onerror = ...;
```
This PR also delays reading the onload/onerror callbacks until the script is done loading.
This behavior is seen on reddit.
> Support dynamic scripts which are added to the DOM before src is set

- src/main.zig
In the docker container, the browser doesn't exit on `CRTL-C` (`SIGINT`).
Catching the signal and exiting fixes the issue.
You can reproduce the issue with the existing version of the docker image
```
$ docker run -ti --rm --name lpd  lightpanda/browser:nightly
```
> exit the browser on SIGINT signal

- src/server.zig
Rather than stack-allocating MAX_MESSAGE_SIZE upfront, we now allocate 32KB and grow the buffer as needed for larger messages, up to MAX_MESSAGE_SIZE.
This will reduce memory usage for drivers that don't send huge payloads (like playwright does).
While not implemented, this would also enable us to set the MAX_MESSAGE_SIZE at runtime (e.g. via a command line option).
> Make the CDP read buffer heap allocated & dynamic

- src/browser/console/console.zig
- src/browser/dom/performance.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/datetime.zig
- src/log.zig
- src/server.zig
There's a flaky performance test that I wanted to fix (1). This led to a couple changes.
1 - Add timestamp() and milliTimestamp() to datetime.zig. Reduce some code
duplication and use better clock_ids where available
2 - Change Performance API to use milliTimestamp and store a u64 instead of a
f64. While the spec says a float, Firefox deals with u64 and implicit
conversion is always available. Makes our APIs simpler.
(1) - https://github.com/lightpanda-io/browser/actions/runs/17313296490/job/49151366798#step:4:131
> Improve clocks

- src/browser/mimalloc.zig
- src/cdp/Node.zig
- src/cdp/testing.zig
- src/testing.zig
The thin mimalloc API is currently defensive around incorrect setup/teardown by guarding against using/destroying the arena when the heap is null, or creating an arena when it already exists.
The only time these checks will fail is when the code is wrong, e.g. trying to use libdom before or after freeing the arena. The current behavior can mask these errors, plus add runtime overhead.
> Switch mimalloc guards to assertions

- src/browser/netsurf.zig
Code like this:
```
var body: ?*ElementHTML = undefined;
const err = documentHTMLVtable(doc_html).get_body.?(doc_html, &body);
try DOMErr(err);
if (body == null) return null;
return @as(*Body, @ptrCast(body.?));
```
Is unsafe. It assumes that libdom will either return an error, or set body to null or a value. However, there are cases (specifically for this API) where libdom returns `DOM_NO_ERR` without setting body (https://github.com/lightpanda-io/libdom/blob/c0df458132162aba136d57ce1ba2179122a9e717/src/html/html_document.c#L1175). In such cases, our wrapper returns an undefined value, which will almost certainly crash the program.
This PR replaces the initial value of optional types from undefined to null (within the libdom wrapper).
> Remove [some] unsafe undefines from netsurf wrapper

- src/TestHTTPServer.zig
- src/browser/ScriptManager.zig
- src/browser/netsurf.zig
- src/browser/xhr/xhr.zig
- src/main.zig
- src/main_wpt.zig
- src/runtime/js.zig
Start unifying test and code
Depends on https://github.com/lightpanda-io/browser/pull/993
There's currently 3 ways to execute a page:
1 - page.navigate (as used in both the 'fetch' and 'serve' commands)
2 - jsRunner as used in unit tests
3 - main_wpt as used in the WPT runner
Both jsRunner and main_wpt replicate the page.navigate code, but in their own
hack-ish way. main_wpt re-implements the DOM walking in order to extract and
execute <script> tags, as well as the needed page lifecycle events.
This PR replaces the existing main_wpt loader with a call to page.navigate. To
support this, a test HTTP server was added. (The test HTTP server is extracted
from the existing unit test test server, and re-used between the two).
There are benefits to this approach:
1 - The code is simpler
2 - More …
> Test http server

- src/browser/Scheduler.zig
- src/browser/ScriptManager.zig
- src/browser/html/window.zig
- src/browser/page.zig
- src/browser/session.zig
- src/cdp/cdp.zig
- src/cdp/domains/fetch.zig
- src/cdp/domains/page.zig
- src/http/Client.zig
- src/http/Http.zig
- src/main.zig
- src/main_wpt.zig
- src/server.zig
- src/testing.zig
There's friction between the CDP polling for data and the page polling for data.
This was previously "improved", by making it so that CDP polling would also active the page polling, and making the page somewhat aware that CDP _might_ need polling.
This has been completely reworked. 
1 - If there's a page with no CDP (./lightpanda fetch), then the page is free to exit as soon as all work is done
2 - If there's a page with CDP, the page is the only one doing the polling. 
3 - If there's no page with CDP, CDP is doing the polling (which is ok, because, without a page, the only data we can get is a CDP message).
This removes the friction and allows the page to poll/timeout smartly, as it has the most context (e.g. information about scheduled tasks).
While this makes the page _slightly_ CDP …
> Http always monitor cdp

- src/http/Client.zig
Ensures that cookies set on the redirect page use the correct host and we don't incorrectly reject cookies.
https://github.com/lightpanda-io/browser/issues/947
> Update the transfer.uri on redirect

- src/browser/ScriptManager.zig
ScriptManager should only ever has one in-flight blockingGet. The is_blocking flag is used to assert this, as well as enforce it in evaluate(). If is_blocking is true, evaluate() exits.
This doesn't work for async scripts however, as they aren't executed via evaluate(), but rather execute directly once complete.
This PR changes the execution behavior of async scripts. They are now only executed in evaluate() (and thus won't execute when is_blocking == true). However, unlike normal/deferred scripts, async scripts continue to execute in their completion order (not their declared order).
Fixes https://github.com/lightpanda-io/browser/issues/1016
> Fix blockingGet during blockingGet

- src/browser/dom/event_target.zig
- src/browser/html/error_event.zig
- src/browser/html/screen.zig
- src/browser/netsurf.zig
- src/tests/html/error_event.html
- src/tests/html/screen.html
I initially thought the bug was related to `error_event`, so I moved the tests to the htmlRunner. Then I realized it wasn't related, but I kept that change in this PR.
https://github.com/lightpanda-io/browser/issues/1015
> Fix the Screen and ScreenOrientation prototype

- src/browser/fetch/Headers.zig
- src/runtime/js.zig
- Only accepts the value if the Js array size matches exactly
Note: tests failing due to fetch branch issue
> jsValueToZig for fixed sized arrays

- src/telemetry/lightpanda.zig
Probably added in the Zig 0.15 migration. Sorry.
> Remove a std.debug.print

- src/browser/Scheduler.zig
- src/browser/page.zig
Like Chrome, the NetworkIdle and NetworkAlmostIdle will only be sent if the condition (no network requests / <= 2 network requests) holds for at least 500ms
Also merged runHighPriority and runLowPriority as they are now always run together (but we still only block/wait for high priority tasks).
> Send NetworkIdle and NetworkAlmostIdle notifications after 500ms delay

- src/runtime/js.zig
This just cleans up the persistent `PromiseResolver` in the dynamic import path. Should help with reducing memory usage.
> Clean Up Persistent Promises in Dynamic Import

- src/browser/mime.zig
- src/browser/page.zig
- src/browser/xhr/xhr.zig
`Mime` is changed to store the received charset value and use it as-is. We used to match the charset value for pre-known cases. Seem to be solving #1045.
As a follow-up commit, we can add support for charset value validation as specified in [RFC 2978](https://datatracker.ietf.org/doc/rfc2978/).
> Mime: charset identification changes

- .github/workflows/e2e-test.yml
- src/http/Client.zig
With proxy auth interception we had a crash (with puppeteer or playwright scenarios)
```
DEBUG cdp : request intercept . . . . . . . . . . . . . . . . [+2411ms]
state = continue with auth
id = 1
response = ProvideCredentials
thread 173974 panic: integer overflow
/home/pierre/wrk/browser/src/http/Client.zig:233:22: 0x3268ee5 in continueTransfer (lightpanda)
self.intercepted -= 1;
^
/home/pierre/wrk/browser/src/cdp/domains/fetch.zig:316:52: 0x3269eba in continueWithAuth__anon_129776 (lightpanda)
try bc.cdp.browser.http_client.continueTransfer(transfer);
^
/home/pierre/wrk/browser/src/cdp/domains/fetch.zig:42:53: 0x31e5012 in processMessage__anon_114148 (lightpanda)
.continueWithAuth => return continueWithAuth(cmd),
^
/home/pierre/wrk/browser/src/cdp/cdp.zig:206:95: 0x31e4339 in …
```
> Fix auth interception integer overflow

- src/browser/css/parser.zig
- src/browser/css/selector.zig
- src/cdp/cdp.zig
- src/cdp/domains/dom.zig
- src/cdp/domains/network.zig
- src/cdp/domains/page.zig
- src/cdp/domains/runtime.zig
- src/cdp/domains/target.zig
Adjust CDP support to improve compatibility with [patchright-nodejs](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-nodejs) client.
Some issues in progress
patchright sends `disposeOnDetach: true`. We didn't implement it for now.
:information_source: It raises a warning.
https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext
patchright sends `pierce: true`. We didn't implement it for now.
:information_source: I turned the error into a log warning.
https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-describeNode
```console
> {"id":38,"method":"Page.createIsolatedWorld","params":{"frameId":"TID-1","grantUniveralAccess":true,"worldName":"utility"},"sessionId":"SID-1"}
< {"id":38,"result":{"executionContextId":2},"sessionId":"SID-1"} …
```
> Patchright compatibility

- src/app.zig
- src/browser/ScriptManager.zig
- src/browser/page.zig
- src/browser/xhr/xhr.zig
- src/http/Client.zig
- src/http/Http.zig
- src/main.zig
- src/testing.zig
Allows appending a value (separated by a space) to the existing Lightpanda/X.Y user agent.
> Add --user_agent_suffix argument

- src/browser/dom/MessageChannel.zig
Removes error return in `postMessage`, we still missing the implementation for `transfer` & `options` but function seem to work for other cases.
> Relaxed `MessagePort.postMessage`

- src/cdp/Node.zig
- src/cdp/domains/dom.zig
chromedp expects the nodeId starts to 1.
A start to 0 make it enter in infinite loop b/c it expects the Go's default int, ie 0, to be nil from a map to stop the loop. If the 0 index is set, it will loop...
> cdp: start nodeId from 1 instead of 0

- build.zig.zon
- src/browser/html/elements.zig
- src/runtime/js.zig
- src/tests/html/script/dynamic_import.html
- src/tests/html/script/import.html
- src/tests/html/script/import.js
- src/tests/html/script/import2.js
- src/tests/testing.js
Replaces https://github.com/lightpanda-io/browser/pull/913
> Dynamic import caching

- src/browser/SlotChangeMonitor.zig
- src/browser/dom/element.zig
- src/browser/dom/event_target.zig
- src/browser/netsurf.zig
- src/browser/page.zig
- src/tests/html/slot.html
- src/tests/testing.js
The first time a `slotchange` event is registered, we setup a SlotChangeMonitor on the page. This uses a global (ugh) MutationEvent to detect slot changes.
We could improve the perfomance of this by installing a MutationEvent per custom element, but a global is obviously a lot easier.
Our MutationEvent currently fired _during_ the changes. This is problematic (in general, but specifically for slotchange). You can image something like:
```
slot.addEventListener('slotchange', () => {
// do something with slot.assignedNodes()
});
```
But, if we dispatch the `slotchange` during the MutationEvent, assignedNodes will return old nodes. So, our SlotChangeMonitor uses the page scheduler to schedule dispatches on the next tick.
> Dispatch slotchange event

- src/browser/dom/element.zig
- src/browser/netsurf.zig
- src/tests/dom/element.html
This PR adds support for `insertAdjacentHTML`. It currently missing XML parsing and `TrustedHTML` support, yet sites seem to prefer HTML and string variant only.
> Support `Element#insertAdjacentHTML`

- src/browser/html/window.zig
- src/tests/window/window.html
This PR adds `window.onload` getter & setter functions and a relevant test.
> Add `window.onload` getter and setter

- src/browser/ScriptManager.zig
- src/browser/mimalloc.zig
- src/browser/page.zig
- src/runtime/js.zig
- src/testing.zig
- src/tests/html/script/dynamic_import.html
Allows dynamic imports to be loading asynchronously. I know reddit isnt the best example, since it doesn't fully load, but this reduced the load time from ~7.2s to ~4.8s.
> nonblocking dynamic imports

- src/browser/ScriptManager.zig
- src/browser/mimalloc.zig
- src/browser/page.zig
- src/cdp/cdp.zig
- src/http/Client.zig
- src/runtime/js.zig
- src/runtime/testing.zig
- src/testing.zig
- src/tests/html/script/dynamic_import.html
Builds on top of https://github.com/lightpanda-io/browser/pull/1088
Where https://github.com/lightpanda-io/browser/pull/1088 focuses on improve async module loading, this PR improve normal (aka blocking) module loading.
> Concurrent blocking imports

- src/browser/fetch/Request.zig
- src/browser/fetch/Response.zig
- src/browser/streams/ReadableStream.zig
- src/browser/streams/ReadableStreamDefaultController.zig
- src/browser/streams/ReadableStreamDefaultReader.zig
- src/runtime/js.zig
- src/tests/streams/readable_stream.html
There's always going to be ambiguity between a string and a Uint8Array. We already had TypedArray(u8) as a discriminator when _returning_ values. But now the type is also used by mapping JS values to Zig. To support this efficiently when probing the union, the typed array mapping logic was extracted into its own function (so that it can be used by the probe).
> Better support for Uint8Array in ReadableStream

- src/browser/html/window.zig
- src/tests/window/window.html
scroll alias for scrollTo
add get_scrollX and get_scrollY, along with their aliases: pageXOffset and pageYOffset. These always return 0, unless scroll or scrollTo are called.
> Improve window scroll

- src/browser/events/mouse_event.zig
- src/cdp/cdp.zig
- src/cdp/domains/log.zig
- src/log.zig
Currently, this hooks a single log.Interceptor into the logging framework, but changing it to take a list shouldn't be too hard. Biggest issue is who will own it, as we'd need an allocator to maintain a list / lookup (which log doesn't currently have).
Uses logFmt format, and, for now, always filters out debug messages and a few particularly verbose scopes.
> Emit Log.addEntry
