lightpanda-io/browser

.github/workflows/build.yml

Relates to https://github.com/lightpanda-io/project/issues/106

ci: add linux amd64 nightly build

---

.github/workflows/build.yml

ci: target cpu x86_64_v3+aes for compatibility

---

.github/actions/install/action.yml
.github/workflows/zig-fmt.yml
.gitignore
README.md
src/async/Client.zig
src/async/stream.zig
src/main_wpt.zig

Relates with https://github.com/lightpanda-io/project/issues/107

upgrade to zig 0.13

---

.gitmodules
build.zig
src/browser/browser.zig
src/browser/loader.zig
src/http/Client.zig

see https://github.com/ziglang/zig/compare/master...ianic:zig:tls23 for integration in std.http.Client
The PR needs zig 0.13 to work
fix #259
depends on #260

use tls.zig with async client

---

src/browser/loader.zig

use 64KB for header buffer

---

src/html/window.zig

dom: first draft for window setTimeout

---

src/cdp/cdp.zig

and avoid error.ProcessFdQuotaExceeded error

cdp: close dir in dumpFile

---

.gitignore
Dockerfile
Makefile
build.zig

This PR changes the organization and paths of external libs (libiconv, netsurf libs, mimalloc) to handle several OS and ARCH outputs.

Multi build

---

src/browser/browser.zig

browser: don't stop processing page on error status code

---

src/main_shell.zig

Quick follow up on https://github.com/lightpanda-io/browser/pull/348 to fix shell compilation

Fix shell main

---

Dockerfile

docker: update zig v8

---

.github/workflows/zig-test.yml

upgrade vendor/zig-js-runtime

---

src/server.zig

see https://github.com/torvalds/linux/commit/5b0af621c3f6ef9261cf6067812f2fd9943acb4b
fix #373

server: REUSEPORT is not allowed on unix socket

---

src/cdp/cdp.zig
src/cdp/runtime.zig
src/cdp/target.zig
src/server.zig

cdp: use an enum for SessionID

---

src/server.zig

depends on https://github.com/lightpanda-io/zig-js-runtime/pull/275

upgrade tigerbeetle

---

.github/actions/install/action.yml
.github/workflows/build.yml
Dockerfile

Add the linux aarch64 version to nightly build release.
Add ARCH argument to the Dodckerfile.
Relates with #417 and #326

Linux aarch64 build

---

src/url.zig

url: accept about:blank

---

src/browser/dom/attribute.zig
src/browser/dom/cdata_section.zig
src/browser/dom/character_data.zig
src/browser/dom/comment.zig
src/browser/dom/document.zig
src/browser/dom/document_fragment.zig
src/browser/dom/document_type.zig
src/browser/dom/element.zig
src/browser/dom/node.zig
src/browser/dom/processing_instruction.zig
src/browser/dom/text.zig
src/browser/html/document.zig
src/browser/html/elements.zig
src/runtime/js.zig

Based on: https://github.com/lightpanda-io/browser/pull/541
Adds the "node" subtype to types

Set Node subtypes

---

src/browser/dom/namednodemap.zig

To fix the WPT regression which isn't a regression.

add indexed_get to namednodemap

---

.github/actions/install/action.yml
Dockerfile
build.zig.zon
src/browser/browser.zig
src/main.zig
src/main_wpt.zig
src/runtime/js.zig

This makes functions like new Intl.DateTimeFormat() not crash.

initialize ICU

---

src/browser/dom/element.zig
src/browser/html/svg_elements.zig

These are the same changes as https://github.com/lightpanda-io/browser/pull/570
Just with the scope fixes in place, so awaiting those PRs to merge

Svgelement dummy2

---

src/browser/dom/dom.zig
src/browser/dom/dom_parser.zig

This adds in an implementation of the `DOMParser`.

add DOMParser

---

src/cdp/domains/dom.zig

Depends on: https://github.com/lightpanda-io/browser/pull/673
Implements: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getBoxModel
Last api needed for Chromedp/click

Dom.getBoxModel

---

src/browser/env.zig
src/browser/html/document.zig
src/browser/html/elements.zig
src/browser/html/form.zig
src/browser/html/select.zig
src/browser/netsurf.zig
src/browser/page.zig
src/browser/xhr/form_data.zig

FormData takes two optional parameters: a form and a submitter.
Building the FormData from these is a first step in supporting form submission.
Basic extension of the HTMLForm element. There was more work done on the Select web api, because the netsurf implementation isn't great. But all of the input elements will need to have their web api extended.

FormData constructor form & submitter parameter

---

Makefile

Update WPT submodule, now includes xhr/formdata tests.

Add debug log level to make build-dev and add new make run-debug

---

src/http/client.zig

The fix is in `keepIdle` (previously `put`). When the pool is full and the oldest connection is released, the connection was only being partially cleaned up.
To make this a little more tidy, the IdleConnection class is now the ConnectionManager and is responsible for creating and destroying connections (and managing the idle pool).

Fix connection memory leak

---

flake.lock
flake.nix

Updates the `flake.nix` for Zig `0.14.1`.

Update flake.nix for Zig 0.14.1

---

src/browser/html/window.zig

I guess this should eventually become a configuration option - what time is too long and should they be skipped or just be run sooner?
But for now, this unblocks from fetching a site like DDG which does a setTimeout of 2 minutes.

Skip long setTimeout/setInterval

---

build.zig.zon
src/browser/netsurf.zig
src/browser/page.zig

zig-v8-fork update simply removes a couple std.debug statements

Update zig-v8-fork + zig fmt fix

---

Dockerfile

https://github.com/lightpanda-io/browser/issues/711

Update zig filename for new pattern used in 0.14.1+

---

Makefile

fix makebuilddev

---

src/browser/page.zig
src/runtime/js.zig

Built on top of https://github.com/lightpanda-io/browser/pull/776
Currently, if there's an internal navigation event, we continue to process the page normally. This has negative performance implication, and can result in user-scripts producing unexpected results.
For example, imagine a page with a script that does.
```js
if (x) {
form.submit();
}
reloadProduct();
```
The call to `form.submit()` should stop the script from executing. And, if the page has 10 other <script> tags after this, they shouldn't be loaded nor executed.
This code terminates the execution of the current script on an internal navigation event, and stops the rest of the page from load.
While I believe this creates a more "correct" behavior, it also introduces new edge cases. There's no a period of time, between the …

Terminate execution on internal navigation

---

src/browser/dom/element.zig
src/browser/renderer.zig

WPT expects these values are part of the DOMRect
https://github.com/lightpanda-io/wpt/blob/main/resources/testdriver.js#L7-L10

add top, left, bottom, right to DOMRect

---

src/browser/dom/document.zig
src/browser/dom/dom.zig
src/browser/dom/range.zig

This adds a pretty basic implementation of the `AbstractRange` and `Range`.

add AbstractRange and Range

---

src/browser/dump.zig

https://github.com/lightpanda-io/browser/issues/800

dump script tag's text content as-is

---

src/browser/dom/exceptions.zig

https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException

DOMException constructor

---

.github/workflows/build.yml

make the arm version compatible with cortex A72 and superior (raspberry pi 4)

Arm compat

---

src/browser/dom/range.zig

https://developer.mozilla.org/en-US/docs/Web/API/Range/selectNodeContents

range.selectNodeContents

---

src/browser/css/parser.zig
src/browser/css/selector.zig

Optimize pseudo-selector parsing. Make comparison case insensitive, bucket comparisons by length, and process input as integers.

Accept popover-over pseudo selector

---

src/http/Client.zig

Fix compilation error

---

src/http/Http.zig

https://github.com/lightpanda-io/browser/issues/982

Don't panic if no certs are available

---

build.zig.zon
src/runtime/js.zig

Depends on https://github.com/lightpanda-io/zig-v8-fork/pull/91

Log unhandled promise rejection

---

build.zig.zon
flake.lock
flake.nix

This both updates the flake to use Zig 0.15.1 and also ensures that it compiles with those dependencies.

Update Nix Flake (Zig 0.15.1)

---

src/browser/dom/event_target.zig
src/browser/netsurf.zig
src/tests/events/custom.html

Depends on: https://github.com/lightpanda-io/libdom/pull/38

Event window bubble

---

src/url.zig

This fixes #1093 and allows URLs to traverse back to their root.  it also adds in a regression test specifically for that case.

Fix URL `stitch` Issue with parent traversal
